### ISSUE TITLE
Build Failed : NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation

### ISSUE THREAD

**Issue by Samiepapa** [Samiepapa/DECA#1]
```
$ python demos/demo_reconstruct.py -i TestSamples/examples/ --saveDepth True --saveObj True
/home/yongilcho/.virtualenvs/DECA/lib/python3.8/site-packages/torch/cuda/__init__.py:125: UserWarning:
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
creating the FLAME Decoder
trained model found. load /home/yongilcho/reposit/DECA/data/deca_model.tar
/home/yongilcho/.virtualenvs/DECA/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
Traceback (most recent call last):
  File "demos/demo_reconstruct.py", line 130, in <module>
    main(parser.parse_args())
  File "demos/demo_reconstruct.py", line 49, in main
    deca = DECA(config = deca_cfg, device=device)
  File "/home/yongilcho/reposit/DECA/decalib/deca.py", line 50, in __init__
    self._setup_renderer(self.cfg.model)
  File "/home/yongilcho/reposit/DECA/decalib/deca.py", line 53, in _setup_renderer
    set_rasterizer(self.cfg.rasterizer_type)
  File "/home/yongilcho/reposit/DECA/decalib/utils/renderer.py", line 39, in set_rasterizer
    load(name='standard_rasterize_cuda',
  File "/home/yongilcho/.virtualenvs/DECA/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 963, in load
    return _jit_compile(
  File "/home/yongilcho/.virtualenvs/DECA/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1170, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/yongilcho/.virtualenvs/DECA/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1264, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "/home/yongilcho/.virtualenvs/DECA/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1593, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "/home/yongilcho/.virtualenvs/DECA/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1414, in _get_cuda_arch_flags
    raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
ValueError: Unknown CUDA arch (8.6) or GPU not supported
```

**Comment by Samiepapa** [comment]
1) CUDA 버전 확인

```
$ nvidia-smi
Mon Feb  7 19:52:48 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 495.46       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   22C    P8    22W / 350W |      5MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:2E:00.0 Off |                  N/A |
|  0%   23C    P8    17W / 350W |     71MiB / 24265MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  Off  | 00000000:41:00.0 Off |                  N/A |
|  0%   23C    P8    26W / 350W |      5MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  Off  | 00000000:61:00.0 Off |                  N/A |
|  0%   23C    P8    28W / 350W |      5MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2668      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A      2668      G   /usr/lib/xorg/Xorg                 55MiB |
|    1   N/A  N/A      2978      G   /usr/bin/gnome-shell               14MiB |
|    2   N/A  N/A      2668      G   /usr/lib/xorg/Xorg                  4MiB |
|    3   N/A  N/A      2668      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```

2) CUDA 11.3 버전에 맞는 stable한 pytorch 버전 설치하기 (https://pytorch.org/get-started/locally/ 참고)
```
pip3 install torch==1.10.2+cu113 torchvision==0.11.3+cu113 torchaudio==0.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```

3) 설치하면서 발생한 아래 버전 mismatch한 패키지 업데이트 하기
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
kornia 0.4.0 requires torch<1.7.0,>=1.6.0, but you have torch 1.10.2+cu113 which is incompatible.
```
```
$ pip3 install --upgrade kornia
```
